// <auto-generated />
using System;
using System.Text.Json;
using IKP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IKP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009103239_DiagnosticDefinitionReferences")]
    partial class DiagnosticDefinitionReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Areas.DiagnosticArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ImportanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "ImportanceScore");

                    b.ToTable("DiagnosticAreas", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AutomaticScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("EffectiveScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ErrorGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ManualScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("OverrideAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OverrideUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveScore");

                    b.HasIndex("ErrorGroupId")
                        .IsUnique();

                    b.HasIndex("EffectiveScore", "CalculatedAt");

                    b.ToTable("ErrorCriticalities", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticalityFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Contribution")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ErrorCriticalityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("ErrorCriticalityId", "DefinitionId")
                        .IsUnique();

                    b.ToTable("ErrorCriticalityFactors", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Code")
                        .IsUnique();

                    b.HasIndex("GroupId", "IsActive", "SortOrder");

                    b.ToTable("DiagnosticDefinitions", "diagnostics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000001"),
                            Code = "INFORMATION",
                            DescriptionKey = "Diagnostic.Severity.Information.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.Severity.Information",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000002"),
                            Code = "WARNING",
                            DescriptionKey = "Diagnostic.Severity.Warning.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.Severity.Warning",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000003"),
                            Code = "ERROR",
                            DescriptionKey = "Diagnostic.Severity.Error.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.Severity.Error",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000004"),
                            Code = "CRITICAL",
                            DescriptionKey = "Diagnostic.Severity.Critical.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.Severity.Critical",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000001"),
                            Code = "NEW",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.New.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.New",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000002"),
                            Code = "INVESTIGATING",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.Investigating.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.Investigating",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000003"),
                            Code = "KNOWN",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.Known.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.Known",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000004"),
                            Code = "FIX_PLANNED",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.FixPlanned.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.FixPlanned",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000005"),
                            Code = "FIXED",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.Fixed.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.Fixed",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000006"),
                            Code = "MONITORING",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.Monitoring.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.Monitoring",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000007"),
                            Code = "RESOLVED",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.Resolved.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.Resolved",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000008"),
                            Code = "IGNORED",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.Ignored.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.Ignored",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000009"),
                            Code = "WONT_FIX",
                            DescriptionKey = "Diagnostic.ErrorGroupStatus.WontFix.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.ErrorGroupStatus.WontFix",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000001"),
                            Code = "OCCURRENCE_RATE",
                            DescriptionKey = "Diagnostic.CriticalityFactor.OccurrenceRate.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.OccurrenceRate",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000002"),
                            Code = "AFFECTED_USERS",
                            DescriptionKey = "Diagnostic.CriticalityFactor.AffectedUsers.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.AffectedUsers",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000003"),
                            Code = "AFFECTED_USER_RATIO",
                            DescriptionKey = "Diagnostic.CriticalityFactor.AffectedUserRatio.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.AffectedUserRatio",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000004"),
                            Code = "FEATURE_IMPORTANCE",
                            DescriptionKey = "Diagnostic.CriticalityFactor.FeatureImportance.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.FeatureImportance",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000005"),
                            Code = "TREND",
                            DescriptionKey = "Diagnostic.CriticalityFactor.Trend.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.Trend",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000006"),
                            Code = "FAILURE_RATE",
                            DescriptionKey = "Diagnostic.CriticalityFactor.FailureRate.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.FailureRate",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000007"),
                            Code = "REGRESSION",
                            DescriptionKey = "Diagnostic.CriticalityFactor.Regression.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.Regression",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000008"),
                            Code = "BUSINESS_IMPACT",
                            DescriptionKey = "Diagnostic.CriticalityFactor.BusinessImpact.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.BusinessImpact",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000009"),
                            Code = "SUPPORT_IMPACT",
                            DescriptionKey = "Diagnostic.CriticalityFactor.SupportImpact.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.SupportImpact",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000010"),
                            Code = "DATA_LOSS_RISK",
                            DescriptionKey = "Diagnostic.CriticalityFactor.DataLossRisk.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.CriticalityFactor.DataLossRisk",
                            SortOrder = 100
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000001"),
                            Code = "MINUTE",
                            DescriptionKey = "Diagnostic.MetricBucketType.Minute.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.MetricBucketType.Minute",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000002"),
                            Code = "HOUR",
                            DescriptionKey = "Diagnostic.MetricBucketType.Hour.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.MetricBucketType.Hour",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000003"),
                            Code = "DAY",
                            DescriptionKey = "Diagnostic.MetricBucketType.Day.Description",
                            GroupId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.MetricBucketType.Day",
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinitionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("DiagnosticDefinitionGroups", "diagnostics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "DIAGNOSTIC_SEVERITY",
                            DescriptionKey = "Diagnostic.DefinitionGroup.Severity.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.DefinitionGroup.Severity",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "ERROR_GROUP_STATUS",
                            DescriptionKey = "Diagnostic.DefinitionGroup.ErrorGroupStatus.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.DefinitionGroup.ErrorGroupStatus",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "CRITICALITY_FACTOR",
                            DescriptionKey = "Diagnostic.DefinitionGroup.CriticalityFactor.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.DefinitionGroup.CriticalityFactor",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "METRIC_BUCKET_TYPE",
                            DescriptionKey = "Diagnostic.DefinitionGroup.MetricBucketType.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Diagnostic.DefinitionGroup.MetricBucketType",
                            SortOrder = 40
                        });
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosticAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FingerprintVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSeenVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSeenVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SeverityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DiagnosticAreaId");

                    b.HasIndex("LastOccurredAt");

                    b.HasIndex("SeverityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("Fingerprint", "FingerprintVersion")
                        .IsUnique();

                    b.ToTable("ErrorGroups", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Errors.ErrorOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Context")
                        .HasColumnType("jsonb")
                        .HasColumnName("ContextSnapshot");

                    b.Property<Guid>("ErrorGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ErrorGroupId", "OccurredAt");

                    b.ToTable("ErrorOccurrences", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Statistics.ErrorMetricBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BucketDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BucketTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ErrorGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FirstOccurrenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastOccurrenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Occurrences")
                        .HasColumnType("bigint");

                    b.Property<long>("UniqueUsers")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt");

                    b.HasIndex("BucketTypeId", "BucketStart");

                    b.HasIndex("ErrorGroupId", "BucketStart");

                    b.HasIndex("ErrorGroupId", "BucketTypeId", "BucketStart", "BucketDurationMinutes")
                        .IsUnique();

                    b.ToTable("ErrorMetricBuckets", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Statistics.ErrorStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AffectedUserRatio")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ErrorGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrowthRate")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<long>("OccurrencesLast7Days")
                        .HasColumnType("bigint");

                    b.Property<long>("OccurrencesLastDay")
                        .HasColumnType("bigint");

                    b.Property<long>("OccurrencesLastHour")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalOccurrences")
                        .HasColumnType("bigint");

                    b.Property<long>("UniqueUsers")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersLast7Days")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersLastDay")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersLastHour")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt");

                    b.HasIndex("ErrorGroupId")
                        .IsUnique();

                    b.ToTable("ErrorStatistics", "diagnostics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Employees", "app");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Logs.AuditActionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("AuditActions", "app_logs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "CREATE",
                            DescriptionKey = "Audit.Action.Create.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Audit.Action.Create",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "UPDATE",
                            DescriptionKey = "Audit.Action.Update.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Audit.Action.Update",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "DELETE",
                            DescriptionKey = "Audit.Action.Delete.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Audit.Action.Delete",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "RESTORE",
                            DescriptionKey = "Audit.Action.Restore.Description",
                            IsActive = true,
                            IsSystem = true,
                            NameKey = "Audit.Action.Restore",
                            SortOrder = 40
                        });
                });

            modelBuilder.Entity("IKP.Domain.Entities.Logs.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntitySchema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntitySchema", "EntityType", "EntityId");

                    b.ToTable("AuditLogs", "app_logs");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Logs.AuditLogChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.ToTable("AuditLogChanges", "app_logs");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticality", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", "ErrorGroup")
                        .WithOne("Criticality")
                        .HasForeignKey("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticality", "ErrorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorGroup");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticalityFactor", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticality", "ErrorCriticality")
                        .WithMany("Factors")
                        .HasForeignKey("ErrorCriticalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("ErrorCriticality");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinition", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinitionGroup", "Group")
                        .WithMany("Definitions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Areas.DiagnosticArea", "DiagnosticArea")
                        .WithMany("ErrorGroups")
                        .HasForeignKey("DiagnosticAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinition", "SeverityDefinition")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinition", "StatusDefinition")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiagnosticArea");

                    b.Navigation("SeverityDefinition");

                    b.Navigation("StatusDefinition");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Errors.ErrorOccurrence", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", "ErrorGroup")
                        .WithMany("Occurrences")
                        .HasForeignKey("ErrorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IKP.Domain.ValueObjects.Diagnostics.ErrorActor", "Actor", b1 =>
                        {
                            b1.Property<Guid>("ErrorOccurrenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SessionId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SessionId");

                            b1.Property<Guid?>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("UserId");

                            b1.HasKey("ErrorOccurrenceId");

                            b1.HasIndex("UserId");

                            b1.ToTable("ErrorOccurrences", "diagnostics");

                            b1.WithOwner()
                                .HasForeignKey("ErrorOccurrenceId");
                        });

                    b.OwnsOne("IKP.Domain.ValueObjects.Diagnostics.ErrorApplicationContext", "Application", b1 =>
                        {
                            b1.Property<Guid>("ErrorOccurrenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApplicationId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ApplicationId");

                            b1.Property<string>("ApplicationVersion")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ApplicationVersion");

                            b1.Property<string>("ClientInstanceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ClientInstanceId");

                            b1.Property<string>("MachineId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("MachineId");

                            b1.Property<string>("Platform")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Platform");

                            b1.HasKey("ErrorOccurrenceId");

                            b1.HasIndex("ApplicationVersion");

                            b1.HasIndex("Platform");

                            b1.ToTable("ErrorOccurrences", "diagnostics");

                            b1.WithOwner()
                                .HasForeignKey("ErrorOccurrenceId");
                        });

                    b.OwnsOne("IKP.Domain.ValueObjects.Diagnostics.ErrorExceptionDetails", "Exception", b1 =>
                        {
                            b1.Property<Guid>("ErrorOccurrenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExceptionType")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ExceptionType");

                            b1.Property<string>("Message")
                                .HasColumnType("text")
                                .HasColumnName("ExceptionMessage");

                            b1.Property<string>("SourceFile")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SourceFile");

                            b1.Property<int?>("SourceLineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("SourceLineNumber");

                            b1.Property<string>("SourceMethod")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SourceMethod");

                            b1.Property<string>("StackTrace")
                                .HasColumnType("text")
                                .HasColumnName("StackTrace");

                            b1.HasKey("ErrorOccurrenceId");

                            b1.ToTable("ErrorOccurrences", "diagnostics");

                            b1.WithOwner()
                                .HasForeignKey("ErrorOccurrenceId");
                        });

                    b.OwnsOne("IKP.Domain.ValueObjects.Diagnostics.ErrorRequestContext", "Request", b1 =>
                        {
                            b1.Property<Guid>("ErrorOccurrenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CorrelationId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CorrelationId");

                            b1.Property<string>("Endpoint")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Endpoint");

                            b1.Property<string>("HttpMethod")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("HttpMethod");

                            b1.Property<string>("RequestId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("RequestId");

                            b1.Property<string>("Route")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Route");

                            b1.HasKey("ErrorOccurrenceId");

                            b1.HasIndex("CorrelationId");

                            b1.HasIndex("RequestId");

                            b1.ToTable("ErrorOccurrences", "diagnostics");

                            b1.WithOwner()
                                .HasForeignKey("ErrorOccurrenceId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();

                    b.Navigation("Application")
                        .IsRequired();

                    b.Navigation("ErrorGroup");

                    b.Navigation("Exception")
                        .IsRequired();

                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Statistics.ErrorMetricBucket", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinition", "BucketTypeDefinition")
                        .WithMany()
                        .HasForeignKey("BucketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", "ErrorGroup")
                        .WithMany()
                        .HasForeignKey("ErrorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BucketTypeDefinition");

                    b.Navigation("ErrorGroup");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Statistics.ErrorStatistics", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", "ErrorGroup")
                        .WithOne("Statistics")
                        .HasForeignKey("IKP.Domain.Entities.Diagnostics.Statistics.ErrorStatistics", "ErrorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorGroup");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Logs.AuditLog", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Logs.AuditActionDefinition", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Logs.AuditLogChange", b =>
                {
                    b.HasOne("IKP.Domain.Entities.Logs.AuditLog", "AuditLog")
                        .WithMany("Changes")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditLog");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Areas.DiagnosticArea", b =>
                {
                    b.Navigation("ErrorGroups");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Criticality.ErrorCriticality", b =>
                {
                    b.Navigation("Factors");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Definitions.DiagnosticDefinitionGroup", b =>
                {
                    b.Navigation("Definitions");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Diagnostics.Errors.ErrorGroup", b =>
                {
                    b.Navigation("Criticality");

                    b.Navigation("Occurrences");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("IKP.Domain.Entities.Logs.AuditLog", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
